# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

source /usr/share/git-core/contrib/completion/git-prompt.sh

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true

PS1='[\d \A \w$(declare -F __git_ps1 &>/dev/null && __git_ps1 " (%s)") ]$ '

# User specific aliases and functions
alias ll='ls -Flag'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias vip='find . -name "*.inp" -exec vim {} +'
alias spellchk='aspell --lang=en --mode=tex -c'
alias sd='sudo yum -y install'
alias shdwn='sudo shutdown'
alias clx='rm -rf /tmp/vim-latex-live-preview-*'
alias tp='trash-put'
alias ff='firefox &'

# PyNE Environment Settings

export PATH="/home/TheDoctorRAB/.local/bin:${PATH}"

# hpc passwd first half of cableone with the CAP and the numbersymbol at the end
